pipeline:
  name: CI
  identifier: CI
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Github
        repoName: dosullivan557/Devops-coursework
        build: <+input>
  stages:
    - stage:
        name: Test
        identifier: Test
        description: Install, validate, and build the application
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: Install_dependencies
                  spec:
                    shell: Sh
                    command: |-
                      node --version
                      npm --version
                      npm ci
                  timeout: 10m
              - parallel:
                  - step:
                      type: Run
                      name: Formatting
                      identifier: Formatting
                      spec:
                        shell: Sh
                        command: npm run format:verify
                      timeout: 10m
                  - step:
                      type: Run
                      name: Linting
                      identifier: Linting
                      spec:
                        shell: Sh
                        command: npm run lint
                      timeout: 10m
                  - step:
                      type: Run
                      name: TypeScript check
                      identifier: TypeScript_check
                      spec:
                        shell: Sh
                        command: npm run typecheck
                      timeout: 10m
                  - step:
                      type: Run
                      name: Production build
                      identifier: Production_build
                      spec:
                        shell: Sh
                        command: npm run build
                      timeout: 15m
        tags: {}
