pipeline:
  name: CI
  identifier: CI
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Github
        repoName: dosullivan557/Devops-coursework
        build: <+input>
  stages:
    - stage:
        name: Test
        identifier: Test
        description: Validate and build using the local Docker runner
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: Install_dependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: node:22.14.0-slim
                    shell: Sh
                    command: npm ci
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "1"
                  timeout: 10m
              - step:
                  type: Run
                  name: Validate and build
                  identifier: Validate_and_build
                  spec:
                    connectorRef: account.harnessImage
                    image: node:22.14.0-slim
                    shell: Sh
                    command: |-
                      npm run format:verify
                      npm run lint
                      npm run typecheck
                      npm run build
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: "1"
                  timeout: 20m
        tags: {}
